name: Cypress Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      CHOKIDAR_USEPOLLING: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy .env vars
        run: cp .env.prod .env
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:3000'
